/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as BacktestEngineRouteImport } from './routes/backtest-engine'
import { Route as PricingRouteImport } from './routes/pricing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestEngineRoute = BacktestEngineRouteImport.update({
  id: '/backtest-engine',
  path: '/backtest-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/backtest-engine': typeof BacktestEngineRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/backtest-engine': typeof BacktestEngineRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/backtest-engine': typeof BacktestEngineRoute
  '/pricing': typeof PricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-studio' | '/backtest-engine' | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-studio' | '/backtest-engine' | '/pricing'
  id: '__root__' | '/' | '/ai-studio' | '/backtest-engine' | '/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudioRoute: typeof AiStudioRoute
  BacktestEngineRoute: typeof BacktestEngineRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest-engine': {
      id: '/backtest-engine'
      path: '/backtest-engine'
      fullPath: '/backtest-engine'
      preLoaderRoute: typeof BacktestEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudioRoute: AiStudioRoute,
  BacktestEngineRoute: BacktestEngineRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
